### PR TITLE
Add contact: account & kind set from picker

### PR DESCRIPTION
**Pull request by DougReeder**
Tested that added contacts are synced back to Google, after allowUpsync set to true in C+DAV Connector.

In details header, list of linked profiles (contact records) is populated, so you can tell what contacts were linked to make this person record.

Open-WebOS-DCO-1.0-Signed-Off-By: Doug Reeder reeder.29@gmail.com

### CODE REVIEW

**Comment by Garfonso** [comment]
Hm.. somehow the DB watch (or any activity?) seems not to fire for me for C+Dav. Not sure why. But on a manuall sync the new contacts are upsynced.

I just noticed that the phone number does not make it into db, though. Not sure if that is a known issue?

**Comment by DougReeder** [comment]
When I add a contact via the Create New Contact pane, the contact linker immediately creates the person record (but the Contacts app doesn't see the new person until you reload, as it doesn't implement watches yet).  The contact is not synced to Google until a manual sync using the C+DAV app.

I observe the phone number field store and upload to Google just fine.  Will test another back end now.

**Comment by Garfonso** [comment]
Hm. Also the periodic sync does not happen... so something with the activities from c+dav is wrong.. so currently I say contact app does things right. :)

**Comment by morphis** [comment]
Is the activity now triggered with the fixed network confidence level for activitymanager?

**Comment by morphis** [comment]
@DougReeder Can you send a PR to https://github.com/webOS-ports/webos-lib for the webos-lib changes?

**Comment by DougReeder** [comment]
Re: the changes to webos-lib, http://issues.webos-ports.org/issues/831 will be a comprehensive removal of anything in webos-lib that is implemented in enyo-webos.

**Pull request merged**
